class ImageCreate
  class InvalidURLError < StandardError; end

  def self.call(title:, caption:, image_url:)
    Image.transaction do
      image = Image.create!(title: title, caption: caption, image_url: image_url)

      request = AzureClient::Request.new(image_url: image_url)
      response = request.post(AzureClient::UrlHelper.describe_api_url)

      raise InvalidURLError if response.status != 200

      image.autogenerated_description = parsed_description(response.body)
      image.tag_list.add(parsed_tags(response.body))
      image.save!
    end
  end

  def self.parsed_description(response_body)
    JSON.parse(response_body)["description"]["captions"][0]["text"]
  rescue
    'Description unavailable'
  end

  def self.parsed_tags(response_body)
    JSON.parse(response_body)["description"]["tags"]
  rescue
    'Description unavailable'
  end
end
