require 'test_helper'

class ImageCreateTest < ActiveSupport::TestCase
  setup do
    @arguments = { title: "a title", caption: "a caption", image_url: "example.com" }
  end

  test "#call creates a new image successfully when the response status is 200" do
    Faraday::Connection.any_instance.expects(:post).returns(stub(status: 200, body: {}))

    assert_difference 'Image.count', 1 do
      ImageCreate.call(**@arguments)
    end

    assert_equal @arguments[:title], Image.last.title
    assert_equal @arguments[:caption], Image.last.caption
    assert_equal @arguments[:image_url], Image.last.image_url
  end

  test "#call sets the image description to the default description when there is no returned caption from azure" do
    Faraday::Connection.any_instance.expects(:post).returns(stub(status: 200, body: {}))

    ImageCreate.call(**@arguments)

    assert_equal "Description unavailable", Image.last.autogenerated_description
  end

  test "#call sets the image description to the autogenerated description when the azure client returns a caption successfully" do
    Faraday::Connection.any_instance.expects(:post).returns(
      stub(status: 200, body: { description: { captions: [ { text: "foo" } ] } }.to_json)
    )

    ImageCreate.call(**@arguments)

    assert_equal "foo", Image.last.autogenerated_description
  end
end
