class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  VALID_SEARCH_TYPES = %w(title caption tag autogenerated_description)

  def index
    @images = if params[:query].present? && VALID_SEARCH_TYPES.include?(params[:search_type])
      case params[:search_type]
      when "tag"
        Image.tagged_with(params[:query].split(" "), :any => true)
      else
        Image.where("#{params[:search_type]} like ?", "%#{params[:query]}%")
      end
    else
      Image.all
    end
  end

  def new
    @image = Image.new
  end

  def create
    begin
      ImageCreate.call(title: image_params[:title], caption: image_params[:caption], image_url: image_params[:image_url])
    rescue => error
      flash[:error] = error.message
      redirect_to new_image_path
    else
      redirect_to Image.last
    end
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:title, :caption, :image_url)
  end
end
